# These are supported funding model platforms

github:
  - Mostafa-SAID7        # Your GitHub Sponsors username

patreon:
  MostafaSaid            # Your Patreon username

ko_fi:
  MostafaSaid            # Your Ko-fi username

liberapay:
  MostafaSaid            # Your Liberapay username

issuehunt:
  MostafaSaid            # Your IssueHunt username

buy_me_a_coffee:
  mssaid356p            # Your Buy Me a Coffee username

thanks_dev:
  u/gh/MostafaSaid       # Your thanks.dev username

custom:
  - 'https://patreon.com/MostafaSaid'
