api:
  - any:
    - 'src/Market.API/**/*'

domain:
  - any:
    - 'src/Market.Domain/**/*'

application:
  - any:
    - 'src/Market.Application/**/*'

infrastructure:
  - any:
    - 'src/Market.Infrastructure/**/*'

tests:
  - any:
    - 'tests/**/*'

docker:
  - any:
    - 'Dockerfile'
    - 'docker-compose.yml'
    - '.dockerignore'

ci-cd:
  - any:
    - '.github/**/*'
    - '*.json'
    - '*.yml'
    - '*.yaml'
