name: ".NET Format"

on:
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Verify formatting
      run: dotnet format --verify-no-changes
